version: "3"

volumes:
  pg-volume:
    driver: local

services:
  pg:
    image: postgres:10-alpine
    environment: 
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'bookstore'
    volumes:
      - pg-volume:/var/lib/postgresql
    ports: 
      - 5432:5432